apiVersion: v2
name: openproject-wrapper
description: Wrapper Helm chart for deploying OpenProject
type: application

version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: openproject
    repository: https://charts.openproject.org
    version: 13.x.x