openproject:
  develop: false

  ingress:
    enabled: true
    host: openproject-dev.example.com
    path: /
    pathType: Prefix
    tls:
      enabled: false

  openproject:
    https: false
    host: openproject-dev.example.com
    hsts: false
    admin_user:
      password: "change-me-dev-password"
      password_reset: "true"
      name: "OpenProject Admin"
      mail: "admin@example.com"

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 20Gi

  postgresql:
    bundled: true

  memcached:
    bundled: true

  replicaCount: 1
  backgroundReplicaCount: 1

  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi

  workers:
    default:
      replicaCount: 1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "1"
          memory: 2Gi